id: P919FFCF8
initial_creation_type: ocr
source_metadata:
  volumes:
    ed544608957e4485aab2b991aeee6aa1:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ''
      total_pages: 1539
      volume_number: 1
