id: DC43D9C49
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-23T11:07:32+00:00'
last_modified: '2022-05-30T06:44:18.880112+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    f755:
      image_group_id: I1PD95846
      title: ཨེ་ཀ་ནཱ་ཐའི་དོན་འགྲེལ།
      total_pages: 1539
      order: 1
      base_file: f755.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
